name: unit-tests

on:
  push:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: unit-tests
      run: cargo test --verbose